#!/usr/bin/python3

# Quick and hacky Python script
# to generate a lua script with
# a table of minecraft item prices

def main():
    with open("market_prices_table.txt") as file:
        source_text = file.read()
    lines = source_text.splitlines()
    lua_text = """
-- prices.lua

-- Table for prices for different minecraft items and blocks,
-- sorted by category
-- This table was generated by generate_prices.py

"""
    lua_text += "PRICES = {"
    current_category = None
    for line in lines:
        # Ignore empty lines or comment lines
        if line.startswith("#") or len(line) == 0:
            continue
        # Category marker
        elif line.startswith("--"):
            if current_category:
                lua_text += "\n    },\n"
            current_category = line[3:]
            lua_text += "\n    [\"" + current_category + "\"] = {"
        # Price declaration
        else:
            idm, name, single_price, stack_price = line.split("\t")
            if idm.find("/") != -1:
                id1, id2 = idm.split("/")
                lua_text += "\n        {" + id1 + ", 0, \"" + name + "\", " + single_price + "},"
                lua_text += "\n        {" + id2 + ", 0, \"" + name + "\", " + single_price + "},"
            else:
                ids = idm.split(":")
                id = ids[0]
                if len(ids) == 2:
                    meta = ids[1]
                    if meta == "@":
                        meta = "-1"
                else:
                    meta = "0"
                lua_text += "\n        {" + id + ", " + meta + ", \"" + name + "\", " + single_price + "},"
    lua_text += "\n    }\n}\n"
    with open("prices.lua", "w") as file:
        file.write(lua_text)

if __name__ == "__main__":
    main()
